// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: api/user_v1/service.proto

package user_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserEditable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname  string   `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	Username string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Telegram string   `protobuf:"bytes,4,opt,name=telegram,proto3" json:"telegram,omitempty"`
	Discord  string   `protobuf:"bytes,5,opt,name=discord,proto3" json:"discord,omitempty"`
	Email    string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Skills   []string `protobuf:"bytes,7,rep,name=skills,proto3" json:"skills,omitempty"`
}

func (x *UserEditable) Reset() {
	*x = UserEditable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_v1_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEditable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEditable) ProtoMessage() {}

func (x *UserEditable) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEditable.ProtoReflect.Descriptor instead.
func (*UserEditable) Descriptor() ([]byte, []int) {
	return file_api_user_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *UserEditable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserEditable) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *UserEditable) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserEditable) GetTelegram() string {
	if x != nil {
		return x.Telegram
	}
	return ""
}

func (x *UserEditable) GetDiscord() string {
	if x != nil {
		return x.Discord
	}
	return ""
}

func (x *UserEditable) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserEditable) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

type UserServerManaged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PasswordHash []byte                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Activated    bool                   `protobuf:"varint,4,opt,name=activated,proto3" json:"activated,omitempty"`
	Version      int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *UserServerManaged) Reset() {
	*x = UserServerManaged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_v1_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserServerManaged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserServerManaged) ProtoMessage() {}

func (x *UserServerManaged) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserServerManaged.ProtoReflect.Descriptor instead.
func (*UserServerManaged) Descriptor() ([]byte, []int) {
	return file_api_user_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserServerManaged) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserServerManaged) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserServerManaged) GetPasswordHash() []byte {
	if x != nil {
		return x.PasswordHash
	}
	return nil
}

func (x *UserServerManaged) GetActivated() bool {
	if x != nil {
		return x.Activated
	}
	return false
}

func (x *UserServerManaged) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_api_user_v1_service_proto protoreflect.FileDescriptor

var file_api_user_v1_service_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbc, 0x01, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x45, 0x64,
	0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64,
	0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6b,
	0x69, 0x6c, 0x6c, 0x73, 0x22, 0xbb, 0x01, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x4b, 0x65, 0x72, 0x75, 0x70, 0x69, 0x65, 0x2f, 0x44, 0x69, 0x70, 0x6c, 0x6f, 0x6d, 0x61,
	0x56, 0x32, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_user_v1_service_proto_rawDescOnce sync.Once
	file_api_user_v1_service_proto_rawDescData = file_api_user_v1_service_proto_rawDesc
)

func file_api_user_v1_service_proto_rawDescGZIP() []byte {
	file_api_user_v1_service_proto_rawDescOnce.Do(func() {
		file_api_user_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_user_v1_service_proto_rawDescData)
	})
	return file_api_user_v1_service_proto_rawDescData
}

var file_api_user_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_user_v1_service_proto_goTypes = []interface{}{
	(*UserEditable)(nil),          // 0: user_v1.UserEditable
	(*UserServerManaged)(nil),     // 1: user_v1.UserServerManaged
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_user_v1_service_proto_depIdxs = []int32{
	2, // 0: user_v1.UserServerManaged.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_user_v1_service_proto_init() }
func file_api_user_v1_service_proto_init() {
	if File_api_user_v1_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_user_v1_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserEditable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_v1_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserServerManaged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_user_v1_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_user_v1_service_proto_goTypes,
		DependencyIndexes: file_api_user_v1_service_proto_depIdxs,
		MessageInfos:      file_api_user_v1_service_proto_msgTypes,
	}.Build()
	File_api_user_v1_service_proto = out.File
	file_api_user_v1_service_proto_rawDesc = nil
	file_api_user_v1_service_proto_goTypes = nil
	file_api_user_v1_service_proto_depIdxs = nil
}
